pingifes:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pingifesDados
  pool: 5
  host: localhost
  port: 3010
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

sigaa:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: sigaa
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: postgres
  password:
  socket: /var/run/mysqld/mysqld.sock

comum:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: sistemas_comum
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: postgres
  password:
  socket: /var/run/mysqld/mysqld.sock

admin:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: administrativo
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: postgres
  password:
  socket: /var/run/mysqld/mysqld.sock
